package com.budget.app.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Outbound payload for all transaction endpoints.
 *
 * budgetName and goalName are resolved display names (not raw IDs),
 * so the frontend can render them directly without extra lookups.
 *
 * recurringID is non-null when this transaction was auto-generated
 * from a RecurringTransaction template — used by the RECURRING filter
 * on the transactions page.
 */
public class TransactionResponseDTO {

    private Long       transactionID;
    private Long       userID;

    private String     transactionName;
    private BigDecimal transactionAmount;
    private LocalDate  transactionDate;

    /** INCOME | EXPENSE | SAVING */
    private String     transactionType;

    private String     transactionNote;

    // Resolved display names for frontend rendering
    private Long       budgetID;
    private String     budgetName;

    private Long       goalID;
    private String     goalName;

    /**
     * Non-null when this transaction was generated by a RecurringTransaction.
     * The frontend uses this to decide whether to show the 🔁 recurring chip
     * and to include the row in the RECURRING filter.
     */
    private Long       recurringID;

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public Long getTransactionID()                       { return transactionID; }
    public void setTransactionID(Long transactionID)     { this.transactionID = transactionID; }

    public Long getUserID()              { return userID; }
    public void setUserID(Long userID)   { this.userID = userID; }

    public String getTransactionName()                         { return transactionName; }
    public void   setTransactionName(String transactionName)   { this.transactionName = transactionName; }

    public BigDecimal getTransactionAmount()                             { return transactionAmount; }
    public void       setTransactionAmount(BigDecimal transactionAmount) { this.transactionAmount = transactionAmount; }

    public LocalDate getTransactionDate()                          { return transactionDate; }
    public void      setTransactionDate(LocalDate transactionDate) { this.transactionDate = transactionDate; }

    public String getTransactionType()                         { return transactionType; }
    public void   setTransactionType(String transactionType)   { this.transactionType = transactionType; }

    public String getTransactionNote()                         { return transactionNote; }
    public void   setTransactionNote(String transactionNote)   { this.transactionNote = transactionNote; }

    public Long getBudgetID()                { return budgetID; }
    public void setBudgetID(Long budgetID)   { this.budgetID = budgetID; }

    public String getBudgetName()                      { return budgetName; }
    public void   setBudgetName(String budgetName)     { this.budgetName = budgetName; }

    public Long getGoalID()              { return goalID; }
    public void setGoalID(Long goalID)   { this.goalID = goalID; }

    public String getGoalName()                    { return goalName; }
    public void   setGoalName(String goalName)     { this.goalName = goalName; }

    public Long getRecurringID()                     { return recurringID; }
    public void setRecurringID(Long recurringID)     { this.recurringID = recurringID; }
}